### ISSUE TITLE
Webpack loaders should be peerDependencies

### ISSUE THREAD

**Issue by SiAdcock** [guardian/atom-renderer#41]
[Webpack loaders](https://github.com/guardian/atom-renderer/blob/master/webpack/css.js) in this project should be `peerDependencies` not `dependencies`. This is because they are used directly in the `webpack.config.js` of the project that installs this library, not the library itself.

Declaring loaders to be dependencies leads to non-deterministic installation in the project that installs `atom-renderer`. The loaders may be installed in `node_modules` or `node_modules/@guardian/atom-renderer/node_modules`, depending on whether they get hoisted by the package manager. This causes problems for loader module resolution in the Webpack config.

**Comment by regiskuckaertz** [comment]
Somehow I missed the notification for this issue. Will raise a PR asap.

**Comment by paulmr** [comment]
Library has been deprecated and is no longer being maintained.
