### ISSUE TITLE
Improve default renderer

### ISSUE THREAD

**Issue by regiskuckaertz** [guardian/atom-renderer#51]
The current default renderer is all but useful, as it just spits out plain text. The aim is that it is used in client applications that do not need the full behaviour of atoms, such as our dashboards and authoring apps. I propose to instead spit out HTML with the minimal amount of CSS needed and zero JavaScript.

If need be, in the future we may add a `PlainTextAtomRenderer`.

**Comment by paulmr** [comment]
Library has been deprecated and is no longer being maintained.
